name: compress_it
description: A new Flutter project.

publish_to: 'none'

version: 1.1.4+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  auto_route: ^7.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.0
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.0.3
  flutter_native_splash: ^2.3.0
  folder_file_saver: ^2.0.5
  image_compare_slider: ^2.7.0
  image_size_getter: ^2.1.2
  syncfusion_flutter_sliders: ^21.2.8
  syncfusion_flutter_core: ^21.2.8
  percent_indicator: ^4.2.3
  fc_native_image_resize: ^0.3.0
  path_provider: ^2.0.15
  ffmpeg_kit_flutter_audio: ^5.1.0
  just_audio: ^0.9.34
  back_button_interceptor: ^6.0.2
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  image_size_getter_heic: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.4
  icons_launcher: ^2.1.0
  very_good_analysis: ^5.0.0+1

# dart run flutter_native_splash:create
flutter_native_splash:
  color: '#ffffff'
  color_dark: '#212121'
  image: 'assets/images/generated/ic_launcher.png'

# dart run flutter_launcher_icons:main
icons_launcher:
  image_path: 'assets/images/generated/ic_launcher.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#1A1A1A'
      adaptive_foreground_image: 'assets/images/generated/adaptive_ic_launcher.png'
      adaptive_round_image: 'assets/images/generated/adaptive_ic_launcher.png'
      adaptive_monochrome_image: 'assets/images/generated/adaptive_ic_launcher.png'
    ios:
      enable: true

flutter:
  assets:
    - assets/images/
  uses-material-design: true
